apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlcard
  labels:
    app: rlcard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rlcard
  template:
    metadata:
      labels:
        app: rlcard
      annotations:
        k8s.aliyun.com/eci-use-specs: "ecs.c5.large"
        k8s.aliyun.com/eci-spot-strategy: "SpotAsPriceGo"
    spec:
      containers:
        - name: rlcard
          image: registry-vpc.cn-hangzhou.aliyuncs.com/xinghan-docker/rlcard-showdown:1.0.0 #replace it with your exactly <image_name:tags>
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            requests:                         ##必须设置，不然HPA无法运行。
              cpu: 2000m
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rlcard-hpa
  namespace: default
spec:
  scaleTargetRef:                             ##绑定名为nginx的Deployment。
    apiVersion: apps/v1
    kind: Deployment
    name: rlcard
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rlcard
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: rlcard
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rlcard
spec:
  rules:
    - host: rlcard.61week.com
      http:
        paths:
          - path: /
            backend:
              serviceName: rlcard
              servicePort: 80